### PR TITLE
refactor(Select): put select in a portal and close select on outside click

### PR DESCRIPTION
**Pull request by sun-tea**
- [ ] Feature
- [ ] Fix
- [x] Enhancement

## Brief
Select component uses a portal to display its content and an event listener allows the component to close its content when an outside click is made.
I did not use react-onclickoutside as it triggers me an error (don't precisely know why but there is something not working between the component and this lib).

## Todo - Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by sun-tea** [comment]
My tests are currently failing when it must click on an item inside the menu, it does not trigger `handleSelected`, I don't know why yet.

**Comment by Artikodin** [comment]
@sun-tea I've noticed that the `react-onclickoutside` doesn't work cause of the dynamic `child` parameter. When you replace it by a static value `react-onclickoutside` works correctly.
Screen Shot 2019-07-12 at 09 45 56
Hope that gonna help.

**Comment by sun-tea** [comment]
I need to work on that more (same for the Dropdown component as seen with Artium).
In short we need to keep in mind at least 3 constraints. Component must:
- move with the scroll when its container is being scrolled (being "portalled" at the end of the body element thus break that)
- be closed on outside click no matter where the component has been created (inside another portal for example)
- component must not be cropped and especially by its container. A component "portalled" next to its trigger (a button for example) thus breaks this rule.

**Comment by sun-tea** [comment]
Closing this in favour of multiple broken down PRs. First one is https://github.com/tillersystems/Stardust/pull/640

**Pull request closed without merging**
