### PR TITLE
test(avatar): refactor unit test with react-testing-library instead o…

### PR DESCRIPTION
**Pull request by spartDev**
…f enzyme

- [ ] Feature
- [ ] Fix
- [x] Enhancement

## Description
I want to refactor all unit test with [react-testing-library](https://github.com/kentcdodds/react-testing-library) instead of [Enzyme](https://github.com/airbnb/enzyme/). 
[Enzyme](https://github.com/airbnb/enzyme/) is lagging behind in terms of React feature support(https://github.com/airbnb/enzyme/issues/1553).
By design [react-testing-library](https://github.com/kentcdodds/react-testing-library) support all the new stuff.

> The more your tests resemble the way your software is used, the more confidence they can give you.

The approach of this library is to avoid the details of component implementation and to focus on how the tests will give us the confidence for which they are intended. Tests are easier to manage, so refactor (changes to implementation but not functionality) do not break the tests.

For example when you add a new i18n key, test won't break.

@leopoldhoudin @AntoninMarchardDev what do you think ?

https://blog.kentcdodds.com/introducing-the-react-testing-library-e3a274307e65

## Todo - Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AntoninMarchardDev** [comment]
@spartDev @leopoldhoudin according to what you said about i18n feature, I think it could be a good idea to not have to update all snapshots when we change/add a key on locales files.
I'm just a bit worried. We don't know when enzyme will be up to date, and if we change each month the testing library it will be a problem.

**Comment by leopoldhoudin** [comment]
as far as I can remember, you were talking about the advantages it could have compared to enzyme, and in particular the way it renders text translations. you could maybe add an example of this "_better_" behavior.

@AntoninMarchardDev I don't think this is a monthly change. yet, i agree we shouldn't change all the time. 

the real question for me is, how can we migrate from enzyme to this testing library without "_loosing_" too much time.

IMO I think it's pretty good. It could be the right timing to also switch from massive snapshots to better Unit tests using `data-xxx` attributes.

**Comment by spartDev** [comment]
@leopoldhoudin How can we migrate from enzyme:
We could have enzyme and react-testing-library living together. All new tests are made with react-testing-library and old tests will be migrated one by one.

**Comment by leopoldhoudin** [comment]
I'd suggest having the list of all stuff that need to be migrated, and a milestone to "force" us to migrate all tests at some point.

Otherwise looks good to me.

**Comment by spartDev** [comment]
I take care of it this weekend!

**Comment by spartDev** [comment]
@leopoldhoudin I create a project and Milestone
https://github.com/tillersystems/Stardust/projects
https://github.com/tillersystems/Stardust/milestones

**Comment by burrelle** [comment]
Hi there! I saw the issue, I would like to help with the transition with this once it gets approved and merged!

**Comment by spartDev** [comment]
Hi @burrelle, we would be happy if you help us to tackle some [issues]. (https://github.com/tillersystems/Stardust/issues). 
 thx.

**Pull request merged**
